# Set update schedule for each package manager

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "tugrulcan"
    labels:
      - "github actions"

  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "tugrulcan"
    labels:
      - "pip dependencies"
